### ISSUE TITLE
[Enhancement] Allow query by strain name

### ISSUE THREAD

**Issue by corneliusroemer** [cevo-public/LAPIS#19]
Often I just have the strain name of a sequence.

Right now, I don't seem to be able to download an open sequence just by strain name, that's a shame:

The [docs](https://cov-spectrum.ethz.ch/public/#introduction) say: 
> The endpoints details, aa-mutations, nuc-mutations, fasta, and fasta-aligned can additionally be filtered by these attributes:
> 
> genbankAccession
> sraAccession
> gisaidEpiIsl

Would be great to add strain name to that list. Things like `USA/AR-CDC-LC0345834/2021`

**Comment by chaoran-chen** [comment]
Sorry, the documentation is not up-to-date! It is however already possible:

https://cov-spectrum.ethz.ch/public/api/v1/sample/details?strain=England%2FMILK-1AE62C1%2F2021
