### ISSUE TITLE
ENH: Allow specification of multiple Genbank accession numbers using `OR` operator for mulit-sequence fasta download

### ISSUE THREAD

**Issue by corneliusroemer** [cevo-public/LAPIS#39]
I'd like to download multiple sequences in one go using the fasta endpoint.

However, I can't find any details in the specification about how to select multiple accession numbers. If I simply add multiple query parameters, will they be added with an `OR` operator, instead of as usual `AND`?

https://cov-spectrum.ethz.ch/public/#introduction

**Comment by chaoran-chen** [comment]
Hi @corneliusroemer. That is currently not possible.

**Comment by corneliusroemer** [comment]
Ah that's a shame, then let's make a feature request ;)

Use case: specify Genbank accession numbers and link directly into Nextclade, so people don't need to manually download fastas :)

**Comment by chaoran-chen** [comment]
Ah, that's an interesting use case!

(Alternatively, Nextclade could maybe accept multiple fasta files? ;))

**Comment by corneliusroemer** [comment]
I think I expressed myself not clearly. It's possible to provide a hosted FASTA instead of manually uploading, like this:
https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=https://api.allorigins.win/raw?url=https://pastebin.com/raw/WDycMW47

However, in this case, I still need to manually download from NCBI, then paste into pastebin.

It'd be amazing if I could just use LAPIS, attach a few NCBI accession numbers and boom, Nextclade downloads automatically and analyzes, cutting out the manual download and pastebin thing.

Trying to make it even easier for people to discover Nextclade ;) and maybe it shows people how good covSpectrum is, too, new use case ideas!

**Comment by corneliusroemer** [comment]
Ah I see, then I misunderstood you ;) 

That's a good idea, in the past I've wanted to allow spiking of sequences with some standard clades so that one can compare one's sample directly in mutation view. It was apparently tricky internally so has stalled for now.

Let's see, maybe I can convince @ivan-aksamentov

**Comment by chaoran-chen** [comment]
Try https://lapis.cov-spectrum.org/open/v1/sample/fasta?pangoLineage=B.1.1.7&limit=10&genbankAccession=MZ039713,MZ039682,OV522182 :)

**Comment by corneliusroemer** [comment]
Ok, works beautifully, will tweet! :) 
https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=https://lapis.cov-spectrum.org/open/v1/sample/fasta?genbankAccession=OM647790,OM647768,OM647353,OM647096
