### ISSUE TITLE
Aligned files should not line-break in browser view

### ISSUE THREAD

**Issue by corneliusroemer** [cevo-public/LAPIS#50]
Encoding of aligned files should be so the browser doesn't linebreak on `-`
https://mpox-lapis.gen-spectrum.org/v1/sample/fasta-aligned?downloadAsFile=false

**Comment by chaoran-chen** [comment]
Do you know how this could be done (if at all possible)? The content type is already `text/x-fasta`. Do you have an example site where the browser does not break the lines on `-`?

**Comment by chaoran-chen** [comment]
I don't think that we can influence how a browser displays a fasta file and it also does not seem to be an actual issue to me.
