### ISSUE TITLE
GISAID instance of lapis cov-spectrum

### ISSUE THREAD

**Issue by ktmeaton** [cevo-public/LAPIS#55]
Was there once a GISAID instance of the LAPIS cov-spectrum API, and is that no longer available? I was pretty sure this query used to work:

`https://lapis.cov-spectrum.org/gisaid/v1/sample/nuc-mutations?pangoLineage=BA.5.1`

But now only the open instance returns data:

`https://lapis.cov-spectrum.org/open/v1/sample/nuc-mutations?pangoLineage=BA.5.1`

I'm guessing it was either removed or requires GISAID credentials to be supplied? I was having trouble finding documentation for this change, sorry if this is already described somewhere. Or maybe I imagined it all along 😄

**Comment by chaoran-chen** [comment]
Hi @ktmeaton, the GISAID instance of LAPIS may only be used by CoV-Spectrum (due to GISAID's terms&conditions). We are unfortunately not allowed to provide you access to it. (If you are interested and have access to GISAID's data, we can help you set up a LAPIS instance on your own server.)
