### ISSUE TITLE
Accept POST requests with parameters in the body

### ISSUE THREAD

**Issue by chaoran-chen** [cevo-public/LAPIS#56]
All the endpoints that support filters currently take the filters as query parameters. This however limits the size of the requests and does not support filtering for a very long list of identifiers. Therefore, the endpoints should also support POST and be able to take the parameters from the request body.

**Comment by theosanderson** [comment]
IMO it would be cool if somewhere (CovSpectrum or LAPIS) there was a way of feeding in a URL which returns a list of IDs as the query. This would mean you could link to (pseudocode) `http://covspectrum.org?query=http://api.arbitrarysite.org/getClade?clade=23`. (And that wouldn't have to just be clades, it could be some AI way of grouping together sequencing with similar functional properties or whatever)

**Comment by chaoran-chen** [comment]
The main issue was implemented in a6fa2c29c77fb8cce4bfd2092e0a5549a9b56a21

@theosanderson, I moved your idea to https://github.com/cevo-public/cov-spectrum-website/issues/535
