### ISSUE TITLE
Advanced Searches for ORF1ab Mutations Fail

### ISSUE THREAD

**Issue by ndkling** [cevo-public/LAPIS#60]
First, thank you very much for CoV-Spectrum.  When I was a young researcher, I had the chance to visit ETH-Zurich and retain the highest opinion of your institution and work.

On to the issue: when trying to execute queries for mutations in ORF1ab using the [documented notation](https://cov-spectrum.org/about#faq-search-variants) for the web-based CoV-Spectrum (e.g. [ORF1b:662](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=ORF1b%3A662) or [ORF1a:13](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=ORF1a%3A13)), I encounter failure with the string `Unexpected error: Please report it to https://github.com/cevo-public/LAPIS/issues`.  Similar searches in other genes(like [S:484](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=S%3A484) or [N:3](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=N%3A3) or [ORF8:3](https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?variantQuery=ORF8%3A3)) work.

Issuing such queries directly against LAPIS works, e.g. [https://lapis.cov-spectrum.org/open/v1/sample/aggregated?aaMutations=ORF1a:13](https://lapis.cov-spectrum.org/open/v1/sample/aggregated?aaMutations=ORF1a%3A13), making this seem like a front-end bug.

`{
  "errors": [],
  "info": {
    "apiVersion": 1,
    "dataVersion": 1662290766,
    "deprecationDate": null,
    "deprecationInfo": null,
    "acknowledgement": null
  },
  "data": [
    {
      "count": 98121
    }
  ]
}`

So, here I am reporting it.  Your valuable time is appreciated!

**Comment by chaoran-chen** [comment]
Thanks you, @ndkling, for reporting the bug! It should now be fixed.

(Fixed in 40c6a58a3e8f4c6a4b052f0b644fa2688a5b207c)
