### ISSUE TITLE
OriginatingLab is not available through aggregate endpoint

### ISSUE THREAD

**Issue by corneliusroemer** [cevo-public/LAPIS#7]
I would expect this query to return all the originating labs in Switzerland, yet the lab field just seems to be null:
```
https://cov-spectrum.ethz.ch/public/api/v0/sample/aggregated?fields=originatingLab&country=Switzerland
```
returns:
```
{"payload":[{"originatingLab":null,"count":38154}],"errors":[],"info":{"apiVersion":0,"deprecationDate":"2021-08-25","deprecationInfo":"This is a beta version. It will soon be replaced with the official release (version 1). Please send us feedback through https://github.com/cevo-public/LAPIS/issues."}}
```

The documentation states that `originatingLab` should be available for aggregation purposes.

**Comment by chaoran-chen** [comment]
Hi @corneliusroemer. LAPIS uses the [public dataset provided by Nextstrain](https://nextstrain.org/blog/2021-07-08-ncov-open-announcement) and, unfortunately, it does not contain any originating lab information yet (the `originating_lab` is always empty). I've heard the Nextstrain team is working or will work on adding it by integrating another data source. As soon as the data appear in the dataset, it should also become available on LAPIS.
